name: C/C++ CI

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile the program
      run: gcc "cache-process.c" -o cache -lpthread
    - name: Execute the program
      run: ./cache
